#!/bin/env python
"""Test API."""

from xstudio.cli.control import control_main

if __name__ == "__main__":
    control_main()

# #!/bin/bash

# SOURCE="${BASH_SOURCE[0]}"
# while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
#   DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
#   SOURCE="$(readlink "$SOURCE")"
#   [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
# done
# DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$DIR/../share/xstudio/lib"

# exec python "$DIR/../lib/python/xstudio/cli/xstudio_control.py"
