name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.10.1
      with:
        clang-format-version: '13'
        check-path: '.'
        exclude-regex: '^./(extern|src/ui/qml/quickfuture)'
